blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/SkyLostTR/whatsapp-mattermost/blob/main/README.md
    about: Check the documentation for usage instructions
  - name: Security Issue
    url: https://github.com/SkyLostTR/whatsapp-mattermost/blob/main/SECURITY.md
    about: Report security vulnerabilities privately
